blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/yourusername/ingestor-system/discussions
    about: For questions, discussions, or general help regarding the Ingestor System
EOL < /dev/null