mapping:
  "README.md": "README"
  "docs/Home.md": "Home"
  "CONTRIBUTING.md": "Contributing"
  "ORGANIZATION.md": "Project-Organization"
  "DEVELOPMENT_ROADMAP.md": "Development-Roadmap"
  "docs/CLI_ARCHITECTURE.md": "CLI-Architecture"
  "docs/api/API_DESIGN.md": "API-Design"
  "docs/development/wiki_contributions.md": "Wiki-Contribution-Guide"
  "docs/entity_extraction_design.md": "Entity-Extraction-Design"
  "docs/entity_extraction_usage.md": "Entity-Extraction-Usage-Guide"
  "docs/mcp_server_guide.md": "MCP-Server-Guide"
  "docs/error_handling.md": "Error-Handling"
  "docs/parallel_processing.md": "Parallel-Processing"
  "docs/structured_logging.md": "Structured-Logging"
  "docs/performance_profiling.md": "Performance-Profiling"