sidebar:
  - title: Home
    page: Home
  - title: Getting Started
    children:
      - title: Contributing
        page: Contributing
      - title: Project Organization
        page: Project-Organization
      - title: Development Roadmap
        page: Development-Roadmap
  - title: Architecture
    children:
      - title: CLI Architecture
        page: CLI-Architecture
      - title: API Design
        page: API-Design
      - title: CI/CD Pipeline
        page: CI-CD-Pipeline
  - title: Features
    children:
      - title: Entity Extraction
        children:
          - title: Design
            page: Entity-Extraction-Design
          - title: Usage Guide
            page: Entity-Extraction-Usage-Guide
      - title: MCP Server
        page: MCP-Server-Guide
      - title: Custom Commands
        page: Custom-Commands
  - title: Development
    children:
      - title: Error Handling
        page: Error-Handling
      - title: Parallel Processing
        page: Parallel-Processing
      - title: Structured Logging
        page: Structured-Logging
      - title: Performance Profiling
        page: Performance-Profiling
  - title: Operations
    children:
      - title: Parallel Processing Guide
        page: Parallel-Processing-Guide
  - title: Contributing
    children:
      - title: Wiki Contribution Guide
        page: Wiki-Contribution-Guide
      - title: Wiki Setup Guide
        page: Wiki-Setup-Guide