name: Ingestor System CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Lint shell scripts
        run: ./scripts/lint.sh

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev jq file libimage-exiftool-perl poppler-utils ffmpeg

      - name: Install test dependencies
        run: ./scripts/install_test_deps.sh

      - name: Run tests
        run: ./scripts/run_tests.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment structure
        run: |
          mkdir -p .ingestor/{config,databases,logs,tmp}
          cp -r config/* .ingestor/config/

      - name: Verify build
        run: |
          chmod +x ./src/ingestor
          ./src/ingestor --version

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ingestor-system
          path: |
            src/
            config/
            .ingestor/
            package.json
            package-lock.json
            README.md
            LICENSE
          retention-days: 5

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ingestor-system
          path: ./ingestor-system

      - name: Package release
        run: |
          cd ingestor-system
          tar czf ../ingestor-system-${{ github.ref_name }}.tar.gz .
          cd ..
          echo "Release version: ${{ github.ref_name }}" > release-notes.md
          cat README.md >> release-notes.md

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ingestor-system-${{ github.ref_name }}.tar.gz
          body_path: release-notes.md
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}